spring.security.oauth2.client.registration.google.client-id=test
spring.security.oauth2.client.registration.google.client-secret=test
spring.security.oauth2.client.registration.kakao.client-id=test
spring.security.oauth2.client.registration.kakao.client-secret=test

app.oauth.google.client-id=test
app.oauth.google.client-secret=test
app.oauth.kakao.client-id=test
app.oauth.kakao.client-secret=test

public.data.api.key=test